[pytest]
addopts = 
    -v 
    --strict-markers 
    --alluredir=reports/allure-results
    --reruns=2 
    --reruns-delay=1
markers =
    smoke: 冒烟测试
    regression: 回归测试
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*